#!/usr/bin/env python3
"""Export the three-column official Attachment 3 submission CSV."""
from __future__ import annotations

import argparse
import csv
from pathlib import Path


REQUIRED_FIELDS = ("id", "predicted_polarity", "predicted_intensity")
VALID_POLARITIES = {"Negative", "Neutral", "Positive"}


def main() -> None:
    root = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=root / "results/attachment3_predictions.csv",
        help="Prediction CSV generated by predict_attachment3.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=root / "问题2_附件3预测结果.csv",
        help="Three-column official result file.",
    )
    args = parser.parse_args()

    with args.input.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None or not set(REQUIRED_FIELDS).issubset(reader.fieldnames):
            raise ValueError(f"input must contain fields {REQUIRED_FIELDS}")
        rows = [{field: row[field] for field in REQUIRED_FIELDS} for row in reader]

    if not rows:
        raise ValueError("input prediction CSV is empty")
    if len({row["id"] for row in rows}) != len(rows):
        raise ValueError("duplicate sample ids found")
    for row in rows:
        if row["predicted_polarity"] not in VALID_POLARITIES:
            raise ValueError(f"invalid polarity for {row['id']}: {row['predicted_polarity']}")
        intensity = float(row["predicted_intensity"])
        if not -3.0 <= intensity <= 3.0:
            raise ValueError(f"intensity out of range for {row['id']}: {intensity}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=REQUIRED_FIELDS)
        writer.writeheader()
        writer.writerows(rows)
    print(f"exported {len(rows)} rows to {args.output}")


if __name__ == "__main__":
    main()
